services:
  postgres:
    image: postgres:15
    container_name: chat_app
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Hop2005@
      POSTGRES_DB: chat_db
    ports:
      - "5432:5432"
    volumes:
      - chat_postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

volumes:
  chat_postgres_data:

networks:
  chat-network:
    driver: bridge