spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_db
    username: chat_user
    password: chat_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
jwt:
  secret: your-secret-key-here