spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chat_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Hop2005@}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: Hop2005@
      timeout: 2000
  security:
    jwt:
      secret: TaqlmGv1iEDMRiFp/pHuID1+T84IK23DF2KJDBf43sdf24ds2fuA0xXh4GhiUI=
      expiration: 86400

  openapi:
    service:
      api-docs: Telegram API
      server: http://localhost:8080,http://api.dqhdev.io.vn
      title: API Service
      version: 1.0.0

server:
  port: 8080



